export const TASK_MARKDOWN = [
  '---',
  'id: T001',
  'title: Create hello module',
  'action: create',
  'file: src/hello.ts',
  '---',
  '',
  '### Description',
  'Create a hello world module',
  '',
  '### Tests',
  '',
  '- returns expected greeting',
  '',
  '### Scope',
  '',
  '**In bounds:**',
  '- src/hello.ts',
  '',
  '**Out of bounds:**',
  '- unrelated files',
  '',
  '### Evidence',
  '',
  '- hello module exists and exports the expected greeting',
  '',
  '### Implementation Steps',
  '',
  '1. Implement the module',
].join('\n');

export const CODE_RESPONSE = [
  '```typescript',
  'export function hello() { return "hello"; }',
  '```',
].join('\n');
