import type { EngineEvent } from '../../../../engine/events/types.js';

const TRANSCRIPT_ROWLESS_EVENT_TYPES = [
  'workflow_started',
  'workflow_resumed',
  'workflow_complete',
  'workflow_config',
  'spec_rejected',
  'spec_regenerated',
  'plan_approved',
  'plan_rejected',
  'plan_regenerated',
  'all_tasks_done',
  'planner_status',
  'planner_heartbeat',
  'drift_chain_detected',
  'snapshot_created',
  'snapshot_restored',
  'snapshot_restore_conflict',
  'mode_resolved',
  'mode_advice',
  'instant_plan_received',
  'tasks_planned',
  'task_completed',
  'task_escalating',
  'task_tokens',
  'task_review_needed',
  'hint_failed',
  'cost_update',
  'approval_prompted',
  'approval_granted',
  'approval_rejected',
  'approval_sticky_recorded',
  'ipc_server_started',
  'ipc_client_attached',
  'ipc_client_detached',
  'ipc_reconnect_attempt',
  'ipc_reconnect_failed',
  'replay_started',
  'replay_complete',
  'clarifications_collected',
  'clarification_answered',
  'runner_call_stalled',
  'runner_call_stall_cleared',
  'brief_recovery_quality_reported',
  'brief_recovery_auto_repair_exhausted',
  'brief_recovery_attempt_accepted',
  'brief_recovery_attempt_started',
  'brief_recovery_attempt_settled',
  'brief_recovery_attempt_unresolved',
  'brief_recovery_provider_failed',
  'brief_recovery_input_queued',
  'brief_recovery_input_applied',
  'brief_recovery_stale_ignored',
  'brief_recovery_rejected',
  'brief_recovery_refused',
  'brief_recovery_transition',
  'brief_recovery_accepted',
  'brief_generation_published',
  'brief_execution_permit_issued',
] as const satisfies readonly EngineEvent['type'][];

type TranscriptRowlessEventType = (typeof TRANSCRIPT_ROWLESS_EVENT_TYPES)[number];

const transcriptRowlessEventTypes: ReadonlySet<string> = new Set(TRANSCRIPT_ROWLESS_EVENT_TYPES);

export function isTranscriptRowlessEvent(
  event: EngineEvent,
): event is Extract<EngineEvent, { type: TranscriptRowlessEventType }> {
  return transcriptRowlessEventTypes.has(event.type);
}
