export const POOL: readonly string[] = [
  'brief -> implementer',
  'typecheck · lint · test',
  'retry(3) -> escalate',
  'const brief = compile(spec)',
  'while (red) retry()',
  'promote(diff)',
  'evidence.jsonl',
  'real software',
  'lower spend',
  'fewer blind spots',
  'one file per brief',
  '0x2f 0x62 0x72',
  '[ 3 / 7 ]',
  '∴',
  '//',
  '→',
  'T1 ✓',
  'T2 ▸',
  'hash ok',
  'worktree',
];
