export const HEARTBEAT_INTERVAL_MS = 2000;
export const IMPLEMENTER_TIMEOUT_MS = 300_000;
export const STREAM_IDLE_TIMEOUT_MS = 60_000;
export const DETECTION_TIMEOUT_MS = 5_000;
export const DISCOVERY_SUBPROCESS_TIMEOUT_MS = 10_000;
export const DISCOVERY_HTTP_TIMEOUT_MS = 5_000;
