export interface KnownModel {
  name: string;
  isDefault?: boolean;
}

// Each tool should have exactly one entry with isDefault: true
export const KNOWN_PLANNER_MODELS: Record<string, KnownModel[]> = {
  'claude-code': [
    { name: 'claude-sonnet-4-6', isDefault: true },
    { name: 'claude-opus-4-6' },
    { name: 'claude-opus-4-5' },
    { name: 'claude-sonnet-4-5' },
    { name: 'claude-sonnet-4' },
    { name: 'claude-haiku-4-5' },
  ],
  codex: [
    { name: 'gpt-5.4', isDefault: true },
    { name: 'gpt-5.4-mini' },
    { name: 'gpt-5.3-codex' },
    { name: 'gpt-5.3-codex-spark' },
    { name: 'gpt-5.2-codex' },
    { name: 'gpt-5.2' },
    { name: 'gpt-5.1-codex-max' },
    { name: 'gpt-5.1-codex' },
    { name: 'gpt-5.1' },
    { name: 'gpt-5-codex-mini' },
    { name: 'o4-mini' },
    { name: 'o3-mini' },
    { name: 'codex-mini-latest' },
  ],
  aider: [
    { name: 'claude-sonnet-4-6', isDefault: true },
    { name: 'claude-opus-4-6' },
    { name: 'claude-opus-4-5' },
    { name: 'claude-sonnet-4-5' },
    { name: 'claude-haiku-4-5' },
    { name: 'gpt-5.4' },
    { name: 'gpt-5.4-mini' },
    { name: 'gpt-5.3-codex' },
    { name: 'gpt-5.2' },
    { name: 'o4-mini' },
    { name: 'o3-mini' },
    { name: 'deepseek/deepseek-r1' },
    { name: 'deepseek/deepseek-v3.2' },
    { name: 'google/gemini-3-pro' },
  ],
  opencode: [
    { name: 'anthropic/claude-sonnet-4-6', isDefault: true },
    { name: 'anthropic/claude-opus-4-6' },
    { name: 'anthropic/claude-opus-4-5' },
    { name: 'anthropic/claude-sonnet-4-5' },
    { name: 'anthropic/claude-sonnet-4' },
    { name: 'anthropic/claude-haiku-4-5' },
    { name: 'openai/gpt-5.4' },
    { name: 'openai/gpt-5.4-mini' },
    { name: 'openai/gpt-5.2' },
    { name: 'openai/o4-mini' },
    { name: 'google/gemini-3.1-pro-preview' },
    { name: 'google/gemini-3-pro' },
    { name: 'google/gemini-2.5-pro' },
    { name: 'deepseek/deepseek-v3.2' },
    { name: 'deepseek/deepseek-r1' },
  ],
  'agent-sdk': [
    { name: 'claude-sonnet-4-6', isDefault: true },
    { name: 'claude-opus-4-6' },
    { name: 'claude-opus-4-5' },
    { name: 'claude-sonnet-4-5' },
    { name: 'claude-sonnet-4' },
    { name: 'claude-haiku-4-5' },
  ],
  anthropic: [
    { name: 'claude-sonnet-4-6', isDefault: true },
    { name: 'claude-opus-4-6' },
    { name: 'claude-opus-4-5' },
    { name: 'claude-sonnet-4-5' },
    { name: 'claude-sonnet-4' },
    { name: 'claude-haiku-4-5' },
  ],
  openrouter: [
    { name: 'anthropic/claude-sonnet-4.6', isDefault: true },
    { name: 'anthropic/claude-opus-4.6' },
    { name: 'anthropic/claude-opus-4.5' },
    { name: 'anthropic/claude-sonnet-4.5' },
    { name: 'anthropic/claude-haiku-4.5' },
    { name: 'openai/gpt-5.4' },
    { name: 'openai/gpt-5.4-mini' },
    { name: 'openai/gpt-5.2' },
    { name: 'openai/o4-mini' },
    { name: 'google/gemini-3.1-pro-preview' },
    { name: 'google/gemini-3-pro' },
    { name: 'deepseek/deepseek-v3.2' },
    { name: 'deepseek/deepseek-r1-0528' },
    { name: 'meta-llama/llama-4-scout' },
    { name: 'mistralai/mistral-large-latest' },
  ],
  ollama: [
    { name: 'qwen2.5-coder:7b', isDefault: true },
    { name: 'qwen2.5-coder:14b' },
    { name: 'qwen2.5-coder:32b' },
    { name: 'llama3.3:latest' },
    { name: 'deepseek-coder-v2:16b' },
    { name: 'codellama:13b' },
  ],
  'lm-studio': [
    { name: 'qwen2.5-coder-7b', isDefault: true },
    { name: 'qwen2.5-coder-14b' },
    { name: 'qwen2.5-coder-32b' },
    { name: 'llama3.3' },
    { name: 'deepseek-coder-v2-16b' },
    { name: 'codellama-13b' },
  ],
  deepseek: [
    { name: 'deepseek-chat', isDefault: true },
    { name: 'deepseek-coder' },
    { name: 'deepseek-reasoner' },
  ],
};

export const KNOWN_IMPLEMENTER_MODELS: Record<string, KnownModel[]> = {
  ollama: [
    { name: 'qwen2.5-coder:7b', isDefault: true },
    { name: 'qwen2.5-coder:14b' },
    { name: 'qwen2.5-coder:32b' },
    { name: 'llama3.3:latest' },
    { name: 'deepseek-coder-v2:16b' },
    { name: 'codellama:13b' },
    { name: 'starcoder2:7b' },
  ],
  'lm-studio': [
    { name: 'qwen2.5-coder-7b', isDefault: true },
    { name: 'qwen2.5-coder-14b' },
    { name: 'qwen2.5-coder-32b' },
    { name: 'llama3.3' },
    { name: 'deepseek-coder-v2-16b' },
    { name: 'codellama-13b' },
  ],
  deepseek: [
    { name: 'deepseek-chat', isDefault: true },
    { name: 'deepseek-coder' },
    { name: 'deepseek-reasoner' },
  ],
  openrouter: [
    { name: 'anthropic/claude-sonnet-4.6', isDefault: true },
    { name: 'anthropic/claude-opus-4.6' },
    { name: 'anthropic/claude-opus-4.5' },
    { name: 'anthropic/claude-sonnet-4.5' },
    { name: 'anthropic/claude-haiku-4.5' },
    { name: 'openai/gpt-5.4' },
    { name: 'openai/gpt-5.4-mini' },
    { name: 'openai/gpt-5.2' },
    { name: 'openai/o4-mini' },
    { name: 'google/gemini-3.1-pro-preview' },
    { name: 'google/gemini-3-pro' },
    { name: 'deepseek/deepseek-v3.2' },
    { name: 'deepseek/deepseek-r1-0528' },
    { name: 'meta-llama/llama-4-scout' },
    { name: 'mistralai/mistral-large-latest' },
  ],
  anthropic: [
    { name: 'claude-sonnet-4-6', isDefault: true },
    { name: 'claude-opus-4-6' },
    { name: 'claude-opus-4-5' },
    { name: 'claude-sonnet-4-5' },
    { name: 'claude-sonnet-4' },
    { name: 'claude-haiku-4-5' },
  ],
};
